/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 alarm_clock_01_4k.gltf --transform 
Files: alarm_clock_01_4k.gltf [10.06KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\bedroom\alarm_clock_01_4k.gltf\alarm_clock_01_4k-transformed.glb [451.26KB] (-4386%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function AlarmClock(props) {
  const { nodes, materials } = useGLTF("/alarm_clock_01_4k-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.065, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cylinder030.geometry}
          material={materials.alarm_clock_01_Glass}
        />
        <mesh
          geometry={nodes.Cylinder030_1.geometry}
          material={materials.alarm_clock_01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/alarm_clock_01_4k-transformed.glb");
