/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 antiqueRug.gltf --transform 
Files: antiqueRug.gltf [14.35KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\living room\antique_heriz_8708_golden_horn_beige_rugs\antiqueRug-transformed.glb [2.2MB] (-15198%)
Author: 3DImaginationHub (https://sketchfab.com/3DImaginationHub)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/antique-heriz-8708-golden-horn-beige-rugs-a8f38b3236b14d8c9c4792195df0cbb3
Title: ANTIQUE HERIZ 8708 GOLDEN HORN BEIGE RUGS
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/antiqueRug-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['19_ANTIQUE_HERIZ_SERAY_ORANGE_BOTTOM.001']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['19_ANTIQUE_HERIZ_SERAY_ORANGE_TOP.001']} />
    </group>
  )
}

useGLTF.preload('/antiqueRug-transformed.glb')
