/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 bathroom_trash_bin.gltf --transform 
Files: bathroom_trash_bin.gltf [5.08KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\bathroom\bathroom_trash_basket\bathroom_trash_bin-transformed.glb [493.08KB] (-9606%)
Author: gootherts (https://sketchfab.com/gootherts)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/bathroom-trash-basket-e76eb2ed248c42f1921dffcc53cd2e94
Title: bathroom trash basket
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bathroom_trash_bin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.main} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/bathroom_trash_bin-transformed.glb')
