/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 bathroom_assets.gltf --transform 
Files: bathroom_assets.gltf [8.64KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\bathroom\bathroom_assets\bathroom_assets-transformed.glb [63.17KB] (-631%)
Author: wring8 (https://sketchfab.com/wring8)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bathroom-assets-865e8aca42584db190d50c280f670e13
Title: Bathroom Assets
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bathroom_assets-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.BathroomMiscA_Mat} />
    </group>
  )
}

useGLTF.preload('/bathroom_assets-transformed.glb')
