/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [15.99KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\bathroom\bathroom_accesories\scene-transformed.glb [420.43KB] (-2529%)
Author: gorzi (https://sketchfab.com/gorzi90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bathroom-accesories-1103528bef074721a5a54d1a60ea56ab
Title: bathroom accesories
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.002']} position={[6.688, 4.029, 0]} scale={0.194} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} position={[6.688, 4.029, 0]} scale={0.194} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.004']} position={[-3.863, 0, 0.123]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
