/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/bathroom/dlx_-_bathroom_sink_puris_aspekt/bathroomSink.gltf --transform 
Files: public/models/bathroom/dlx_-_bathroom_sink_puris_aspekt/bathroomSink.gltf [12.97KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\bathroomSink-transformed.glb [105.18KB] (-711%)
Author: d-luX (https://sketchfab.com/dluX80)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dlx-bathroom-sink-puris-aspekt-9f4a07d36d934fdd8122978f4ad669e9
Title: dlX - Bathroom Sink (Puris Aspekt)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BathroomSink(props) {
  const { nodes, materials } = useGLTF("/bathroomSink-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Main_dark_0.geometry}
        material={materials.dark}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Handles_Chrome_dark_0.geometry}
        material={materials.Chrome_dark}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Table_wood_0.geometry}
        material={materials.wood}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Drain_Chrome_light_0.geometry}
        material={materials.Chrome_light}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/bathroomSink-transformed.glb");
