/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 brass_pan_01_4k.gltf --transform 
Files: brass_pan_01_4k.gltf [2.68KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\brass_pan_01_4k.gltf\brass_pan_01_4k-transformed.glb [341.48KB] (-12642%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brass_pan_01_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.brass_pan_01.geometry} material={materials.brass_pan_01} />
    </group>
  )
}

useGLTF.preload('/brass_pan_01_4k-transformed.glb')
