/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ClassicNightstand_01_4k.gltf --transfrom 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ClassicNightStand(props) {
  const { nodes, materials } = useGLTF("/ClassicNightstand_01_4k.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ClassicNightstand_01.geometry}
        material={materials.ClassicNightstand_01}
      />
    </group>
  );
}

useGLTF.preload("/ClassicNightstand_01_4k.gltf");
