/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 descansoShagRug.gltf --transform 
Files: descansoShagRug.gltf [15.12KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\readingRoom\descanso_5x7_off_white_shag_rug\descansoShagRug-transformed.glb [630.64KB] (-4071%)
Author: diwhy.life (https://sketchfab.com/diwhy.life)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/descanso-5x7-off-white-shag-rug-266799cf672444ea8d2c480b5c981b02
Title: Descanso 5X7 Off White Shag Rug
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ShagRug(props) {
  const { nodes, materials } = useGLTF("/descansoShagRug-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Rug_Bottom_Rug_Bottom_0.geometry}
        material={materials.Rug_Bottom}
        position={[0, -0.017, 0]}
        rotation={[-1.557, -0.01, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.model_tex_u1_v1_0.geometry}
        material={materials.tex_u1_v1}
        rotation={[-1.557, -0.01, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/descansoShagRug-transformed.glb");
