/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: colinmansfield (https://sketchfab.com/colinmansfield)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/home-floor-plan-empty-658c1aa87c1f4ddabd318c898ecef497
Title: Home Floor Plan (empty)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function EmptyHouse(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.089}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
        {/* cabinets */}
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_0}
        />
        {/* doors */}
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material_0}
        />
        {/* sinks */}
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_0}
        />
        {/* door frames */}
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.material_0}
        />
        {/* walls */}
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_0}
        />
        {/* floor */}
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
