/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/office/several_folders/folders.gltf --transform 
Files: public/models/office/several_folders/folders.gltf [21.24KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\folders-transformed.glb [720.52KB] (-3292%)
Author: janexx (https://sketchfab.com/janexx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/several-folders-1a493b49ef954985ab8057ca66c387d5
Title: Several Folders
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Folders(props) {
  const { nodes, materials } = useGLTF("/folders-transformed.glb");
  return (
    <group {...props} dispose={null} scale={0.009}>
      <mesh
        geometry={nodes.folder_LP_nolabel_Folder_nolabel_0.geometry}
        material={materials.Folder_nolabel}
        position={[409.825, 16.108, 26.505]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.folder_LP_Bills_Folder_Bills_0.geometry}
        material={materials.Folder_Bills}
        position={[417.367, 16.108, 26.505]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.folder_LP_TaxRecords_Folder_TaxRecords_0.geometry}
        material={materials.Folder_TaxRecords}
        position={[424.956, 16.108, 26.505]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.folder_LP_House_Folder_House_0.geometry}
        material={materials.Folder_House}
        position={[432.666, 16.108, 26.505]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.folder_LP_Work_Folder_Work_0.geometry}
        material={materials.Folder_Work}
        position={[442.966, 16.587, 26.505]}
        rotation={[-Math.PI / 2, -0.15, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/folders-transformed.glb");
