/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 food_apple_01_4k.gltf --transform 
Files: food_apple_01_4k.gltf [2.71KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\food_apple_01_4k.gltf\food_apple_01_4k-transformed.glb [333.54KB] (-12208%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/food_apple_01_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.food_apple_01.geometry} material={materials.food_apple_01} />
    </group>
  )
}

useGLTF.preload('/food_apple_01_4k-transformed.glb')
