/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 food_kiwi_01_4k.gltf --transform 
Files: food_kiwi_01_4k.gltf [2.69KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\food_kiwi_01_4k.gltf\food_kiwi_01_4k-transformed.glb [869.74KB] (-32232%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Kiwi(props) {
  const { nodes, materials } = useGLTF("/food_kiwi_01_4k-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.food_kiwi_01.geometry}
        material={materials.food_kiwi_01}
      />
    </group>
  );
}

useGLTF.preload("/food_kiwi_01_4k-transformed.glb");
