/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 handSoapBottle.gltf --transform 
Files: handSoapBottle.gltf [12.93KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\bathroom\hand_soap_bottle\handSoapBottle-transformed.glb [193.46KB] (-1396%)
Author: Sousinho (https://sketchfab.com/sousinho)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/hand-soap-bottle-a78cfed1e1be461e80a34de466016d69
Title: Hand soap bottle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/handSoapBottle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Hand_soap_bottle_T_hand_soap_bottle_0.geometry} material={materials.T_hand_soap_bottle} position={[0, 0, 0.261]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.SM_Hand_soap_bottle001_T_hand_soap_bottle_white_0.geometry} material={materials.T_hand_soap_bottle_white} position={[0, 0, 0.048]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.SM_Hand_soap_bottle002_T_hand_soap_bottle_green_blank_0.geometry} material={materials.T_hand_soap_bottle_green_blank} position={[0, 0, -0.173]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/handSoapBottle-transformed.glb')
