/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 hanging_picture_frame_02_4k.gltf --transform 
Files: hanging_picture_frame_02_4k.gltf [6.43KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\readingRoom\hanging_picture_frame_02_4k.gltf\hanging_picture_frame_02_4k-transformed.glb [477.43KB] (-7325%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hanging_picture_frame_02_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube009.geometry} material={materials.hanging_picture_frame_02_artwork} />
      <mesh geometry={nodes.Cube009_1.geometry} material={materials.hanging_picture_frame_02} />
      <mesh geometry={nodes.Cube009_2.geometry} material={materials.hanging_picture_frame_02_glass} />
    </group>
  )
}

useGLTF.preload('/hanging_picture_frame_02_4k-transformed.glb')
