/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 livingRoomChair.gltf --transform 
Files: livingRoomChair.gltf [7.28KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\living room\living_room_chair\livingRoomChair-transformed.glb [863.17KB] (-11757%)
Author: gavzbetz1 (https://sketchfab.com/gavzbetz1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/living-room-chair-6fab01d8db574699b353038c9be1f591
Title: Living Room Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/livingRoomChair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.meshes0__0.geometry} material={materials.meshes0__0} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/livingRoomChair-transformed.glb')
