/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mantel_clock_01_4k.gltf --transform 
Files: mantel_clock_01_4k.gltf [5.63KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\living room\mantel_clock_01_4k.gltf\mantel_clock_01_4k-transformed.glb [630.49KB] (-11099%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mantel_clock_01_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mantel_clock_01.geometry} material={materials.mantel_clock_01} />
      <mesh geometry={nodes.mantel_clock_01_glass.geometry} material={materials.mantel_clock_01_glass} position={[0, 0.091, 0.056]} />
    </group>
  )
}

useGLTF.preload('/mantel_clock_01_4k-transformed.glb')
