/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 modern_ceiling_lamp_01_4k.gltf --transform 
Files: modern_ceiling_lamp_01_4k.gltf [6.18KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\modern_ceiling_lamp_01_4k.gltf\modern_ceiling_lamp_01_4k-transformed.glb [319.92KB] (-5077%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modern_ceiling_lamp_01_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.modern_ceiling_globe} />
      <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.modern_ceiling_lamp_01_glass} />
    </group>
  )
}

useGLTF.preload('/modern_ceiling_lamp_01_4k-transformed.glb')
