/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/kitchen/kitchen_design_set_v.001/modernKitchen.gltf --transform 
Files: public/models/kitchen/kitchen_design_set_v.001/modernKitchen.gltf [189.64KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\modernKitchen-transformed.glb [7.52MB] (-3868%)
Author: Truong Arch (https://sketchfab.com/kiemtruongkts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kitchen-design-set-v001-47e74e0fab8f43a1b88cbfc0d7f9989f
Title: Kitchen Design Set V.001
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ModernKitchen(props) {
  const { nodes, materials } = useGLTF("/modernKitchen-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material2_48.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.py0243}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_1.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials.pyAM134_14_Cover}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_3.geometry}
        material={materials.py0225}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_4.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_5.geometry}
        material={materials.pyAM134_14_065_Label}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_6.geometry}
        material={materials.py0237}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_7.geometry}
        material={materials.py0238}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_8.geometry}
        material={materials["3300k"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_9.geometry}
        material={materials.pyvray_00f}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_10.geometry}
        material={materials.py0167}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_11.geometry}
        material={materials.py0166}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_12.geometry}
        material={materials.pybiscuit_ourson}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_13.geometry}
        material={materials.pybiscuit_gelatine_chocolat}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_14.geometry}
        material={materials.pybiscuit_bateau}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_15.geometry}
        material={materials.pybiscuit_gelatine_fraise}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_16.geometry}
        material={materials.pybiscuit_gelatine_abricot}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_17.geometry}
        material={materials.pybiscuit_gelatine_citron}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_18.geometry}
        material={materials.pypims_chocolat}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_19.geometry}
        material={materials.pypims_biscuit}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_20.geometry}
        material={materials.py0203}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_21.geometry}
        material={materials.py0204}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_22.geometry}
        material={materials.py0202}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_23.geometry}
        material={materials.pybox_10}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_24.geometry}
        material={materials.pyvray_00asdsd023_22}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_25.geometry}
        material={materials.py0176}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_26.geometry}
        material={materials.py0175}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_27.geometry}
        material={materials.pypepper}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_28.geometry}
        material={materials.pysticker_olive_oil_c}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_29.geometry}
        material={materials.py0235}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_30.geometry}
        material={materials.py0231}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_31.geometry}
        material={materials.py0233}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_32.geometry}
        material={materials.py0234}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_33.geometry}
        material={materials.py0232}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_34.geometry}
        material={materials.pyMaterial_4}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_35.geometry}
        material={materials.pyMaterial_2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_36.geometry}
        material={materials.pyMaterial_3}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_37.geometry}
        material={materials.pyMaterial_5}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_38.geometry}
        material={materials.pyMaterial_7}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_39.geometry}
        material={materials.pym2q11105}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_40.geometry}
        material={materials.py0186}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_41.geometry}
        material={materials.py0218}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_42.geometry}
        material={materials.py0189}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_43.geometry}
        material={materials.pyx10169}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_44.geometry}
        material={materials.pycookie}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_45.geometry}
        material={materials.pyvray_00asdsd005}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_46.geometry}
        material={materials.pycoffee_background}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_47.geometry}
        material={materials.pycoffee}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_49.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/modernKitchen-transformed.glb");
