/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 modern_wooden_cabinet_4k.gltf --transform 
Files: modern_wooden_cabinet_4k.gltf [10.96KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\living room\modern_wooden_cabinet_4k.gltf\modern_wooden_cabinet_4k-transformed.glb [490.43KB] (-4375%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ModernWoodenCabinet(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/modern_wooden_cabinet_4k-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} scale={0.8}>
      <group name="Scene">
        <group
          name="modern_wooden_cabinet_path_l"
          position={[-1.19, 0.164, 0.23]}
        />
        <group
          name="modern_wooden_cabinet_path_r"
          position={[1.19, 0.164, 0.23]}
        />
        <mesh
          name="modern_wooden_cabinet_body"
          geometry={nodes.modern_wooden_cabinet_body.geometry}
          material={materials.modern_wooden_cabinet}
        />
        <mesh
          name="modern_wooden_cabinet_door_l"
          geometry={nodes.modern_wooden_cabinet_door_l.geometry}
          material={materials.modern_wooden_cabinet}
          position={[-1.19, 0.164, 0.23]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/modern_wooden_cabinet_4k-transformed.glb");
