/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 potted_plant_02_4k.gltf --transform 
Files: potted_plant_02_4k.gltf [6.65KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\living room\potted_plant_02_4k.gltf\potted_plant_02_4k-transformed.glb [1.31MB] (-19549%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/potted_plant_02_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.potted_plant_02_pot.geometry} material={materials.potted_plant_02_pot} />
      <mesh geometry={nodes.potted_plant_02_leaves.geometry} material={materials.potted_plant_02_leaves} position={[-0.003, 0.305, 0.001]} />
    </group>
  )
}

useGLTF.preload('/potted_plant_02_4k-transformed.glb')
