/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 potted_plant_04_4k.gltf --transform 
Files: potted_plant_04_4k.gltf [7.08KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\potted_plant_04_4k.gltf\potted_plant_04_4k-transformed.glb [949.64KB] (-13313%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/potted_plant_04_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.potted_plant_04_ground.geometry} material={materials.potted_plant_04} />
    </group>
  )
}

useGLTF.preload('/potted_plant_04_4k-transformed.glb')
