/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 sweet_potato_4k.gltf --transform 
Files: sweet_potato_4k.gltf [2.78KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\sweet_potato_4k.gltf\sweet_potato_4k-transformed.glb [571.14KB] (-20445%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sweet_potato_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sweet_potato.geometry} material={materials.sweet_potato} />
    </group>
  )
}

useGLTF.preload('/sweet_potato_4k-transformed.glb')
