/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/bathroom/toilet/toilet.gltf --transform 
Files: public/models/bathroom/toilet/toilet.gltf [15.14KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\toilet-transformed.glb [383.28KB] (-2432%)
Author: HippoStance (https://sketchfab.com/hippostance)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toilet-132a8ee2af3a40d39d270fbed3d3666c
Title: Toilet
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Toilet(props) {
  const { nodes, materials } = useGLTF("/toilet-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Toilet_Toilet_0.geometry}
        material={materials.Toilet}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/toilet-transformed.glb");
