/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/living room/FlatScreenTv/tv.gltf --transform 
Files: public/models/living room/FlatScreenTv/tv.gltf [7.3KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\tv-transformed.glb [4KB] (45%)
Author: CN Entertainment (https://sketchfab.com/cn-entertainment)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-1b7eff20a86b4cc692bc4222ac1ac252
Title: TV
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Tv(props) {
  const { nodes, materials } = useGLTF("/tv-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TV_49Zoll_Black_0.geometry}
        material={materials.Black}
        position={[2.55, -0.696, -0.022]}
      />
      <mesh
        geometry={nodes.TV_49Zoll_RedLight_0.geometry}
        material={materials.RedLight}
        position={[2.55, -0.696, -0.022]}
      />
      <mesh
        geometry={nodes.TV_49Zoll_Screen1_0.geometry}
        material={materials.Screen1}
        position={[2.55, -0.696, -0.022]}
      />
    </group>
  );
}

useGLTF.preload("/tv-transformed.glb");
