/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 vintage_cabinet_01_4k.gltf --transform 
Files: vintage_cabinet_01_4k.gltf [22.56KB] > D:\OneDrive\Documents\personalProjects\threejs-and-react-projects\react-three-fiber-note-taking-app\public\models\kitchen\vintage_cabinet_01_4k.gltf\vintage_cabinet_01_4k-transformed.glb [878.48KB] (-3794%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vintage_cabinet_01_4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vintage_cabinet_01_door_01.geometry} material={materials.vintage_cabinet_01_glass} position={[-0.898, 1.62, 0.111]} />
      <mesh geometry={nodes.Plane056.geometry} material={materials.vintage_cabinet_01_b} />
      <mesh geometry={nodes.Plane056_1.geometry} material={materials.vintage_cabinet_01_a} />
    </group>
  )
}

useGLTF.preload('/vintage_cabinet_01_4k-transformed.glb')
